######################FINAL EXAM - BIS 679###################################

#THIS IS AN OPEN-NOTE, OPEN INTERNET, IN CLASS EXAM 
#YOU MAY NOT CONTACT OR WORK WITH ANYONE DURING THE EXAM
#ANY QUESTIONS SHOULD BE DIRECTED TO DR.ESSERMAN OR BOYANG LI

#PLEASE SAVE THE FILE AS YOUR LASTNAME_FIRSTNAME_R_FINAL AND UPLOAD TO CANVAS WHEN
#YOU HAVE COMPLETED THE EXAM

#MAKE SURE TO LEAVE ENOUGH TIME FOR UPLOAD.  THE EXAM UPLOAD CLOSES AT 12PM

#PLEASE ENTER YOUR ANSWER TO EACH OF THE 4 QUESTIONS BELOW BETWEEN THE COMMENT
#LINES PROVIDED FOR THAT QUESTION. ONLY INFORMATION ENTERED BETWEEN THOSE LINES 
#WILL BE GRADED

#THIS EXAM WILL BE GRADED OUT OF 100 POINTS.  
# TO RECEIVE FULL CREDIT:
#(1)  CODE MUST BE PROPERLY DOCUMENTED
#(2)  CODE MUST BE COMMENTED OR LABELED 
#(3)  RESULTS MUST BE REPRODUCIBLE

#THE POINT VALUE FOR EACH QUESTION IS AS FOLLOWS:
#QUESTION 1: 25
#QUESTION 2: 20
#QUESTION 3: 30
#QUESTION 4: 25


#MAKE SURE THAT FOR ANY PACKAGES NEEDED TO RUN YOUR CODE 
#YOU CHECK THAT THE PACKAGE IS INSTALLED 
#(AND INSTALL THE PACKAGE IF IT IS NOT ALREADY INSTALLED)
#AND THEN CALL THE LIBRARY SO THAT THE PACKAGE CAN BE USED IN YOUR CODE

#MAKE SURE THAT ONLY THE REQUESTED OUTPUT IS PRINTED TO THE SCREEN

#YOU WILL NEED TO USE DATA SETS PROVIDED IN THE FILE DATA_R_EXAM.R
#PLEASE MODIFY THE WORKING DIRECTORY CODE BELOW TO POINT TO WHERE YOU HAVE 
#SAVED THAT FILE AND USE THE SOURCE CODE BELOW TO CREATE THE DATA SETS .


setwd("R:/Teaching/Programming 2018/Exams/R Exam")
source("DATA_R_EXAM.R")

##############################QUESTION 1########################################
#THE question1 DATA SET CONTAINS A VECTOR OF CONTINUOUS DATA
#WRITE CODE TO 
# (1) CALCULATE THE COEFFICIENT OF VARIATION OF THIS VECTOR
# (2) ESTIMATE THE 95% CONFIDENCE INTERVAL USING 10000 BOOTSTRAP SAMPLES
# (3) PRINT BOTH (1) AND (2) AS A LIST 

#################################################################################


###########################ANSWER QUESTION 1#####################################










#################################################################################


##############################QUESTION 2#########################################
#REWRITE THE FOLLOWING CODE ELIMINATING THE FOR LOOP (TRY TO MAKE IT AS EFFICIENT
#AS POSSIBLE - E.G. COMBINE STEPS WHERE POSSIBLE - BUT MAKE SURE IT WORKS FIRST
#AND FOREMOST.)


#THE FOLLOWING CODE CONDUCTS A SIMULATION TO DETERMINE THE POWER OF THE TWO SAMPLE
#PROPORTION FOR A SAMPLE SIZE OF 100 WHEN THE PROBABILITY OF SUCCESS IS 0.5 IN
#GROUP 1 (X) AND THE PROBABILITY OF SUCCESS IS 0.4 IN GROUP 2 (Y) AND THE TYPE I
#ERROR RATE IS 0.05
#THE CODE PROVIDES THE POWER OF THE TEST AND IT ALSO PRINTS A HISTOGRAM OF THE
#DISTRIBUTION OF X AND Y OVERLAYED
#NOTE: IF YOU REWRITE THE CODE, EVEN WITH THE SAME SEED, YOU MAY NOT GET IDENTICAL RESULTS

#SET THE SEED
set.seed(34567)
#INITIALIZE THE VECTORS
X<-NULL
Y<-NULL
Z<-NULL
p.value<-NULL
pow<-NULL
#RUN 1000 SIMULATIONS
for(i in 1:1000){
  X[i]<-rbinom(1,100,0.5)/100 #GENERATE P1-HAT
  Y[i]<-rbinom(1,100,0.4)/100 #GENERATE P2-HAT
  Z[i]<-(X[i]-Y[i])/sqrt((X[i]*(1-X[i])/100)+(Y[i]*(1-Y[i])/100)) #CALCULATE THE Z STATISTIC
  p.value[i]=2*pnorm(-abs(Z[i])) #CALCULATE THE P-VALUE
  pow[i]<-p.value[i]<0.05 #DETERMINE IF REJECT THE NULL HYPOTHESIS
}
power<-sum(pow)/1000
print(power)
hist(X, col=rgb(0,0,1,0.5), main='Distribution of proportions of two groups', xlab="proportions", breaks=10)
hist(Y, col=rgb(1,0,0,0.5), add=T, breaks=10)
legend("topright", c("X", "Y"), fill=c(rgb(0,0,1,0.5), rgb(1,0,0,0.5)))
#################################################################################


###########################ANSWER QUESTION 2#####################################








#################################################################################


##############################QUESTION 3#########################################
#TURN YOUR ANSWER TO QUESTION 2 INTO A FUNCTION CALLED p2.power 
#WHERE THE FOLLOWING PARAMETERS CAN VARY: 
#THE SEED, NUMBER OF SIMULATIONS, THE SUCCESS PROPORTION IN GROUP 1,
#THE SUCCESS PROPORTION IN GROUP 2, THE SAMPLE SIZE IN GROUP 1, THE SAMPLE SIZE IN GROUP 2,
#AND THE TYPE 1 ERROR RATE.
#SINCE THE CODE IN QUESTION 3 IS ONLY VALID FOR THE NORMAL APPROXIMATION TO THE BINOMIAL
#MAKE SURE THAT YOU CHECK THAT N1*P1 AND N2*P2 ARE BOTH GREATER THAN 5.  IF NOT
#THE USER SHOULD RECEIVE AN ERROR MESSAGE
#THE FUNCTION SHOULD PLOT A HISTOGRAM OF THE DISTRIBUTION OF X AND Y OVERLAYED AND
#RETURN A LIST WITH THE PARAMETERS ENTERED INTO THE FUNCTION (THE CALL)
#AND THE POWER GENERATED FROM THOSE PARAMETERS

#PROVIDE TWO CALLS OF THE FUNCTION
#1) SEED=2030, NUMBER OF SIMULATIONS=1000, THE SUCCESS PROPORTION IN GROUP 1 =0.3
#   THE SAMPLE SIZE IN GROUP 1=200, THE SUCCESS PROPORTION IN GROUP 2 =0.5
#   THE SAMPLE SIZE IN GROUP 2=250, AND THE TYPE I ERROR RATE = 0.05

#2)  SEED=4444, NUMBER OF SIMULATIONS=1000, THE SUCCESS PROPORTION IN GROUP 1 =0.05
#   THE SAMPLE SIZE IN GROUP 1=50, THE SUCCESS PROPORTION IN GROUP 2 =0.2
#   THE SAMPLE SIZE IN GROUP 2=50, AND THE TYPE I ERROR RATE = 0.05

#################################################################################

###########################ANSWER QUESTION 3#####################################







#################################################################################


##############################QUESTION 4#########################################
# THE question4 DATA SET CONTAINS TWO VARIABLES: studyid AND BP
# THE NUMBER OF BP MEASURES PER INDIVIDUAL RANGES FROM 1 TO 8.

# CREATE A DATA SET CALLED bpdata WHICH CONTAINS ONE ROW OF DATA PER INDIVIDUAL
# AND HAS THE FOLLOWING VARIABLES: 
# studyid
# bp.meaures: THE NUMBER OF BP MEASURES THAT AN INDIVIDUAL HAS IN THE DATA SET
# min.bp: MIN OF THE BP MEASURES
# max.bp: MAX OF THE BP MEASURES
# difference: THE DIFFERENCE BETWEEN THE MAXIMUM AND MINIMUM BP (max.bp-min.bp)
#NOTE: IF AN INDIVIDUAL ONLY HAS 1 BP MEASURE THEN min.bp, max.bp AND difference SHOULD BE
#MISSING (NA)
#PRINT THE FIRST 10 OBSERVATIONS IN DESCENDING ORDER BY difference

#################################################################################

###########################ANSWER QUESTION 4#####################################









#################################################################################